services:
  nginx:
    image: nginx:1.27.1-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  php:
    build: .
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:8.4.2
    environment:
      # 🚨 Change if you want to use in production
      MYSQL_ROOT_PASSWORD: root # ⬅︎ 🚨
      MYSQL_DATABASE: appdb
      MYSQL_USER: user # ⬅︎ 🚨
      MYSQL_PASSWORD: password # ⬅︎ 🚨
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root # ⬅︎ 🚨
    ports:
      - "8081:80"
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"   # SMTP port
      - "8025:8025"   # Web interface port

volumes:
  data:
